### ISSUE TITLE
gulp-modules missing

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/gulp-wpdtrt-plugin-bump#16]
```
cd ./wpdtrt-gallery
npm run version
```

```
> wpdtrt-gallery@1.9.0 version /Users/dan/Websites/wpdtrt-gallery
> npm run version --prefix $npm_package_config_wpdtrt_npm_scripts


> wpdtrt-npm-scripts@0.2.2 version /Users/dan/Websites/wpdtrt-gallery/node_modules/wpdtrt-npm-scripts
> node ./scripts/version/plugin-bump.js

/Users/dan/Websites/wpdtrt-gallery/node_modules/wpdtrt-npm-scripts/scripts/version/plugin-bump.js:6
    inputPathBoilerplate: `./${boilerplatePath()}`
                               ^

TypeError: boilerplatePath is not a function
    at Object.<anonymous> (/Users/dan/Websites/wpdtrt-gallery/node_modules/wpdtrt-npm-scripts/scripts/version/plugin-bump.js:6:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

gulp-modules *was* part of wpdtrt-plugin-boilerplate - wpdtrt-map has this.

**Comment by dotherightthing** [comment]
c1a7a49acbb57403c131b956c2775848d944570c

12/10/2019 - Use wpdtrt-gulp

**Comment by dotherightthing** [comment]
This script can therefore be migrated into wpdtrt-npm-scripts and this repo mothballed.

**Comment by dotherightthing** [comment]
See also the placeholder replacement used by Natural Docs config
